
defaults:
  - _self_
  - model: DenseRegDSSResNet
  - dataset: ExpressionDataset # must have a variable "haplotype: bool"

split_mask: True
mask_rate: 0.2
masking: null
validate_every: 1

test: False

get_embeddings: False
agnostic: False
mask_at_test: False
seq_len: 5000
train_splits: 1
fold: 0
tot_epochs: 5
batch_size: 16
learning_rate: 1e-3
weight_decay: 0
save_at: [1, 2, 3, 4, 5]

device: cpu
log_wandb: False
wandb_proj: "lm_eqtl"
run_name: ""

