_target_: model.models.regression.models.RegDSSResNet

_partial_: True

d_input: 3
d_output: 3
d_model: 256
n_layers: 16
dropout: 0
prenorm: False
species_encoder: null
embed_before: True

regression_head: 
 _target_: model.models.regression.models.TransformerRegressionHead
 input_size: 256
 num_layers: 1